- name: configure catalogue
  hosts: catalogue
  become: yes

  vars:
    mongodb_host: mongodb-dev.devopspractice08.online

  tasks:

    - name: Enable NodeJS 20 module
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install NodeJS
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: Create roboshop system user
      ansible.builtin.user:
        name: roboshop
        system: true
        home: /app
        shell: /sbin/nologin
        comment: "roboshop system user"

    - name: Create application directory
      ansible.builtin.file:
        path: /app
        state: directory
        owner: roboshop
        group: roboshop

    - name: Download catalogue artifact
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip

    - name: Unzip catalogue
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes
        owner: roboshop
        group: roboshop

    - name: Install NPM dependencies
      community.general.npm:
        path: /app

    - name: Copy catalogue systemd service
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: Copy Mongo repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present

    - name: Check if catalogue DB exists
      ansible.builtin.command: >
        mongosh --host {{ mongodb_host }} --quiet --eval
        'db.getMongo().getDBNames().indexOf("catalogue")'
      register: catalogue_output

    - name: Print Mongo check result
      ansible.builtin.debug:
        var: catalogue_output.stdout

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start catalogue service
      ansible.builtin.systemd:
        name: catalogue
        enabled: yes
        state: started