[mongodb]
mongodb-dev.devopspractice08.online

[catalogue]
catalogue-dev.devopspractice08.online

[redis]
redis-dev.devopspractice08.online

[user]
user-dev.devopspractice08.online

[cart]
cart-dev.devopspractice08.online

[mysql]
mysql-dev.devopspractice08.online

[shipping]
shipping-dev.devopspractice08.online

[rabbitmq]
rabbitmq-dev.devopspractice08.online

[payment]
payment-dev.devopspractice08.online

[frontend]
frontend-dev.devopspractice08.online




 
[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321 

MONGODB_HOST=mongodb-dev.devopspractice08.online
REDIS_HOST=redis-dev.devopspractice08.online
USER_HOST=user-dev.devopspractice08.online
CATALOGUE_HOST=catalogue-dev.devopspractice08.online
PAYMENT_HOST=payment-dev.devopspractice08.online
FRONTEND_HOST=frontend-dev.devopspractice08.online
RABBITMQ_HOST=rabbitmq-dev.devopspractice08.online
MYSQL_HOST=mysql-dev.devopspractice08.online
SHIPPING_HOST=shipping-dev.devopspractice08.online
