# ansible-playbook -i localhost, \ -e '{"instances":["mongodb","mysql","redis","catalogue","user","payment","shipping","cart"]}' \roboshop.yaml
- name: create ec2 intance and route53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-0397ae3d261c3d2e4 
    ami_id: ami-0220d79f3f480ecf5
    domain_name: devopspractice08.online
    env: dev
    action : create 
    instances:
    - mongodb 
    - catalogue
    - frontend
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}-{{ env }}"
      
      tags:
        project: roboshop
        component: "{{ item }}"
        Environment: "{{ env }}"
        name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"
    register: ec2_output
    when: action == "create" 
    
  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
    when: action == "create" 


  - name: create route53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}-{{ env }}.{{ domain_name}}" # mongodb.devopspractice08.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true

    loop: "{{ ec2_output.results }}"  #list 
    when: action == "Create" 


  - name: create route53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ roboshop }}-{{ env }}.{{ domain_name}}" # roboshoop.devopspractice08.online, 
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_output.results }}" 
    when: # and
    - item.item == "frontend"
    - action == "create" 

  - name: delete route53 records
    amazon.aws.route53:
      state: absent
      zone: "{{ domain_name }}"
      record: "{{ item }}-{{ env }}.{{ domain_name }}"
      type: A
      ttl: 1
    loop: "{{ instances }}"
    when: action == "destroy"
    

  - name: delete ec2 instance
    amazon.aws.ec2_instance:
      state: absent
      name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"

        
 

